title: Deep Learning as Fluid Dynamics
description: This is a blog of an ongoing research that formulates deep learning as fluid dynamics problem. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

# This will require each of these plugins automatically.
plugins: ['jekyll-scholar']

scholar:
    sort_by: year
    order: descending